FileVersion = 1
Dependencies = {corlib = "*", BJSON = "*"}

[Project]
Name = "BJSON.Test"
TargetType = "BeefTest"
StartupObject = "BJSON.Test.Program"

[Configs.Test.Win64]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/TestSuites\", \"$(BuildDir)/TestSuites\")"]

[[Configs.Test.Win64.DistinctOptions]]
Filter = ""
